import os, sys

INP = {}

INP['PXI'] = """
!setting for x06sa EIGER 16M data
JOB={jobs}
MAXIMUM_NUMBER_OF_JOBS={njobs}
MAXIMUM_NUMBER_OF_PROCESSORS={nproc}
CLUSTER_NODES={nodes}
! for this experiment:
ORGX=              {beamX}
ORGY=              {beamY}
DETECTOR_DISTANCE= {detectorDistance}
OSCILLATION_RANGE= {oscillationAngle}
X-RAY_WAVELENGTH=  {wavelength}
NAME_TEMPLATE_OF_DATA_FRAMES={xtalname}
DATA_RANGE=        {firstIndex} {numFrames}
SPOT_RANGE=        {firstIndex} {numFrames}
BACKGROUND_RANGE=  {firstIndex} {lastIndex}
REFERENCE_DATA_SET= {referenceData}
SPACE_GROUP_NUMBER={SG}
UNIT_CELL_CONSTANTS= {unit_cell}
TEST_RESOLUTION_RANGE= 10.0 5.0
!REIDX=   0  0 -1  0  0 -1  0  0 -1  0  0  0
REFINE(IDXREF)=BEAM AXIS ORIENTATION CELL
REFINE(INTEGRATE)=BEAM ORIENTATION POSITION !CELL AXIS
REFINE(CORRECT)=POSITION BEAM ORIENTATION CELL AXIS
FRIEDEL'S_LAW={friedel}
STRICT_ABSORPTION_CORRECTION=FALSE ! but read Tips_and_Tricks in XDSwiki
! parameters with changes wrt default values:
TRUSTED_REGION=0.00 1.2
VALUE_RANGE_FOR_TRUSTED_DETECTOR_PIXELS=4000. 30000.
!MINIMUM_ZETA=0.05
CORRECTIONS=DECAY MODULATION ABSORP !default value
INCLUDE_RESOLUTION_RANGE=50 {highres}
! parameters specifically for this detector and beamline:
DETECTOR=EIGER NX=4150 NY=4371 QX=0.075  QY=0.075 !EIGER 16M
! Defines path to the Dectris neggia library (to use H5ToXds comment this line out)
LIB={lib}
MINIMUM_VALID_PIXEL_VALUE=0  OVERLOAD=3000000
DIRECTION_OF_DETECTOR_X-AXIS=1 0 0
DIRECTION_OF_DETECTOR_Y-AXIS=0 1 0
INCIDENT_BEAM_DIRECTION=0 0 1
ROTATION_AXIS=1 0 0
FRACTION_OF_POLARIZATION=0.99
POLARIZATION_PLANE_NORMAL=0 1 0
SENSOR_THICKNESS=0.45
!EXCLUSION OF HORIZONTAL DEAD AREAS OF THE EIGER 16M DETECTOR + ONE PIXEL ON EACH SIDE
 UNTRUSTED_RECTANGLE=    0 4151    513  553
 UNTRUSTED_RECTANGLE=    0 4151   1064 1104
 UNTRUSTED_RECTANGLE=    0 4151   1615 1655
 UNTRUSTED_RECTANGLE=    0 4151   2166 2206
 UNTRUSTED_RECTANGLE=    0 4151   2717 2757
 UNTRUSTED_RECTANGLE=    0 4151   3268 3308
 UNTRUSTED_RECTANGLE=    0 4151   3819 3859
!EXCLUSION OF VERTICAL DEAD AREAS OF THE EIGER 16M DETECTOR + ONE PIXEL ON EACH SIDE
 UNTRUSTED_RECTANGLE= 1029 1042      0 4372
 UNTRUSTED_RECTANGLE= 2069 2082      0 4372
 UNTRUSTED_RECTANGLE= 3109 3122      0 4372
NUMBER_OF_PROFILE_GRID_POINTS_ALONG_ALPHA/BETA=21 !used by: INTEGRATE
MINIMUM_NUMBER_OF_PIXELS_IN_A_SPOT={min_pix_spot}
MINIMUM_FRACTION_OF_INDEXED_SPOTS=0.1
SEPMIN=4 CLUSTER_RADIUS=2
STRONG_PIXEL={strong_pixel}
"""
#================================
INP['PXII'] = """
!setting for x10sa Pilatus 6M data
JOB={jobs}
MAXIMUM_NUMBER_OF_JOBS={njobs}
MAXIMUM_NUMBER_OF_PROCESSORS={nproc}
CLUSTER_NODES={nodes}
! for this experiment:
ORGX=              {beamX}
ORGY=              {beamY}
DETECTOR_DISTANCE= {detectorDistance}
OSCILLATION_RANGE= {oscillationAngle}
X-RAY_WAVELENGTH=  {wavelength}
NAME_TEMPLATE_OF_DATA_FRAMES={xtalname} CBF
DATA_RANGE=        {firstIndex} {numFrames}
SPOT_RANGE=        {firstIndex} {numFrames}
BACKGROUND_RANGE=  {firstIndex} {lastIndex}
REFERENCE_DATA_SET= {referenceData}
SPACE_GROUP_NUMBER={SG}
UNIT_CELL_CONSTANTS= {unit_cell}
!REIDX=   0  0 -1  0  0 -1  0  0 -1  0  0  0
REFINE(IDXREF)=BEAM AXIS ORIENTATION CELL !DISTANCE
REFINE(INTEGRATE)=POSITION DISTANCE BEAM ORIENTATION !CELL AXIS
REFINE(CORRECT)=POSITION DISTANCE BEAM ORIENTATION CELL AXIS
FRIEDEL'S_LAW={friedel}
STRICT_ABSORPTION_CORRECTION=FALSE ! but read Tips_and_Tricks in XDSwiki
! parameters with changes wrt default values:
TRUSTED_REGION=0.00 1.2
VALUE_RANGE_FOR_TRUSTED_DETECTOR_PIXELS=8000. 30000.
!MINIMUM_ZETA=0.05
CORRECTIONS=DECAY MODULATION ABSORP !default value
INCLUDE_RESOLUTION_RANGE=50 {highres}
! parameters specifically for this detector and beamline:
DETECTOR=PILATUS NX=2463 NY=2527 QX=0.172  QY=0.172 !PILATUS 6M
MINIMUM_VALID_PIXEL_VALUE=0  OVERLOAD=1048500
DIRECTION_OF_DETECTOR_X-AXIS=1 0 0
DIRECTION_OF_DETECTOR_Y-AXIS=0 1 0
INCIDENT_BEAM_DIRECTION=0 0 1
ROTATION_AXIS=1 0 0
FRACTION_OF_POLARIZATION=0.99
POLARIZATION_PLANE_NORMAL=0 1 0
SENSOR_THICKNESS=0.32
!UNTRUSTED_RECTANGLE= 487  495     1 2527
!UNTRUSTED_RECTANGLE= 981  989     1 2527
!UNTRUSTED_RECTANGLE=1475 1483     1 2527
!UNTRUSTED_RECTANGLE=1969 1977     1 2527
!UNTRUSTED_RECTANGLE=   1 2463   195  213
!UNTRUSTED_RECTANGLE=   1 2463   407  425
!UNTRUSTED_RECTANGLE=   1 2463   619  637
!UNTRUSTED_RECTANGLE=   1 2463   831  849
!UNTRUSTED_RECTANGLE=   1 2463  1043 1061
!UNTRUSTED_RECTANGLE=   1 2463  1255 1273
!UNTRUSTED_RECTANGLE=   1 2463  1467 1485
!UNTRUSTED_RECTANGLE=   1 2463  1679 1697
!UNTRUSTED_RECTANGLE=   1 2463  1891 1909
!UNTRUSTED_RECTANGLE=   1 2463  2103 2121
!UNTRUSTED_RECTANGLE=   1 2463  2315 2333
NUMBER_OF_PROFILE_GRID_POINTS_ALONG_ALPHA/BETA=13 !used by: INTEGRATE
MINIMUM_NUMBER_OF_PIXELS_IN_A_SPOT={min_pix_spot}
MINIMUM_FRACTION_OF_INDEXED_SPOTS=0.10
SEPMIN=4 CLUSTER_RADIUS=2
STRONG_PIXEL={strong_pixel}
"""
#================================================
INP['PXIII']="""
!setting for x06da Pilatus 2M data
JOB={jobs}
MAXIMUM_NUMBER_OF_JOBS={njobs}
MAXIMUM_NUMBER_OF_PROCESSORS={nproc}
CLUSTER_NODES={nodes}
! for this experiment:
ORGX=              {beamX}
ORGY=              {beamY}
DETECTOR_DISTANCE= {detectorDistance}
OSCILLATION_RANGE= {oscillationAngle}
X-RAY_WAVELENGTH=  {wavelength}
NAME_TEMPLATE_OF_DATA_FRAMES={xtalname} CBF
DATA_RANGE=        {firstIndex} {numFrames}
SPOT_RANGE=        {firstIndex} {numFrames}
BACKGROUND_RANGE=  {firstIndex} {lastIndex}
REFERENCE_DATA_SET= {referenceData}
SPACE_GROUP_NUMBER={SG}
UNIT_CELL_CONSTANTS= {unit_cell}
!REIDX=   0  0 -1  0  0 -1  0  0 -1  0  0  0
REFINE(IDXREF)=BEAM AXIS ORIENTATION CELL !DISTANCE
REFINE(INTEGRATE)=POSITION DISTANCE BEAM ORIENTATION !CELL AXIS
REFINE(CORRECT)=POSITION DISTANCE BEAM ORIENTATION CELL AXIS
FRIEDEL'S_LAW={friedel}
STRICT_ABSORPTION_CORRECTION=FALSE ! but read Tips_and_Tricks in XDSwiki
! parameters with changes wrt default values:
TRUSTED_REGION=0.00 1.2
VALUE_RANGE_FOR_TRUSTED_DETECTOR_PIXELS=8000. 30000.
!MINIMUM_ZETA=0.05
CORRECTIONS=DECAY MODULATION ABSORP !default value
INCLUDE_RESOLUTION_RANGE=50 {highres}
! parameters specifically for this detector and beamline:
DETECTOR=PILATUS NX=1475 NY=1679 QX=0.172  QY=0.172 !PILATUS 2M
MINIMUM_VALID_PIXEL_VALUE=0  OVERLOAD=1048500
DIRECTION_OF_DETECTOR_X-AXIS=1 0 0
DIRECTION_OF_DETECTOR_Y-AXIS=0 1 0
INCIDENT_BEAM_DIRECTION=0 0 1
ROTATION_AXIS=1 0 0
FRACTION_OF_POLARIZATION=0.99
POLARIZATION_PLANE_NORMAL=0 1 0
SENSOR_THICKNESS=0.45
!EXCLUDE edge pixels
!EXCLUSION OF VERTICAL DEAD AREAS OF THE PILATUS 2M DETECTOR
!UNTRUSTED_RECTANGLE= 486  496     0 1680
!UNTRUSTED_RECTANGLE= 980  990     0 1680
!EXCLUSION OF HORIZONTAL DEAD AREAS OF THE PILATUS 2M DETECTOR
!UNTRUSTED_RECTANGLE=   0 1476   194  214
!UNTRUSTED_RECTANGLE=   0 1476   406  426
!UNTRUSTED_RECTANGLE=   0 1476   618  638
!UNTRUSTED_RECTANGLE=   0 1476   830  850
!UNTRUSTED_RECTANGLE=   0 1476  1042 1062
!UNTRUSTED_RECTANGLE=   0 1476  1254 1274
!UNTRUSTED_RECTANGLE=   0 1476  1466 1486
NUMBER_OF_PROFILE_GRID_POINTS_ALONG_ALPHA/BETA=13 !used by: INTEGRATE
MINIMUM_NUMBER_OF_PIXELS_IN_A_SPOT={min_pix_spot}
MINIMUM_FRACTION_OF_INDEXED_SPOTS=0.2
SEPMIN=4 CLUSTER_RADIUS=2
STRONG_PIXEL={strong_pixel}
"""
